### PR TITLE
cb-list tags-tags ticket13

### PR DESCRIPTION
**Pull request by CalBoyt**
# Description

Added View All Tags feature to project. You can now click on Tags Management from the menu and view all tags, listed alphabetically. Trello ticket #13: https://trello.com/c/ixhdmhBc/13-13-view-all-tags

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# Testing Instructions

1. git add and git commit whatever you're working on on your branch.
2. git checkout main.
3. git fetch -a.
4. git checkout cb-tags-ticket13.
5. If you don't see the most recent version of my files, git pull origin cb-tags-ticket13.
6. Create the Tabloid MVC database (if not already done) located here: (https://github.com/NewForce-Cohort-8/tabloidmvc-thunder-strike/blob/main/SQL/01_TabloidMVC_Create_DB.sql).
7. Add the seed data for the project (if not already done) located here: (https://github.com/NewForce-Cohort-8/tabloidmvc-thunder-strike/blob/main/SQL/02_TabloidMVC_Seed_Data.sql).
8. Open new query (In the SQL Server Object Explorer, open the TabloidMVC database view, right click, and select New Query).
9. Enter the following query: "SELECT * FROM tag;" and execute by clicking the green triangular button in the query window. The resulting list of tags is what should display when testing the program.
10. Click the execute with debugger solid green button to launch the app.
11. If you are not already logged in, in browser, please go to Login on the nav bar and log in with this email: admin@example.com. This should redirect you back to the home page.
12. On nav bar, click "Tags Management".
13. Verify this takes you to the /Tag route and lists the tags in the DB from your SQL query by name, alphabetically.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by andyhanks — APPROVED** [review]
I have reviewed cb-tags-ticket13. It does display tags when user clicks the Tag Management link. Functions as indicated .

**Review by juan-alcalde — APPROVED** [review]
amazing! tag list works as described!

**Comment by sarahebrooks12** [comment]
- No links to seed data 
- No list of what tags should be showing up or a SQL query to perform to show what tags should be listed

**Comment by Tommy-Spurlock** [comment]
Links to seed data are still broken. Tester also needs to know what they should specifically see when the do the specific task.

**Review by sarahebrooks12 — APPROVED** [review]

**Pull request merged**
