### PR TITLE
JA Edit Post Ticket #8

### PR DESCRIPTION
**Pull request by juan-alcalde**
# Description

The function to edit a post has been completed.

Given a user is viewing a Post that they have written,
when they select the edit option
then they should be presented to an Edit Post Form page.

Given the user wishes to edit the post,
when they edit the form fields and click on the save button,
then the Post should be edited
and the user should be directed back to the Post List.
 
Given the user decides not to edit,
When they the select the option to "Cancel"
then the post should NOT be edited 
And the user should be directed back to the post list page.

Fixes # (issue)
Ticket #8:  https://trello.com/c/n4LzFsFs/8-8-edit-a-post

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# Testing Instructions

1. After making sure you have our repo cloned down into a local repository and have the database added, git fetch --all in the master branch to retrieve this branch named ja-editPost-ticket8 that I have pushed up.
2. git checkout ja-editPost-ticket8 to switch to my branch and open up Visual Studio.
3. create a new database and run the following  TabloidMVC sql script using SQL Server Object Explorer inside Visual Studio :
       -Open a new SQL query
       -Copy the following code into the new SQL query and execute it to create database :
       Follow this [link](https://github.com/NewForce-Cohort-8/tabloidmvc-thunder-strike/blob/main/SQL/01_TabloidMVC_Create_DB.sql) .
  
4. Open a new SQL query for your database,  
   Copy the following code into the new SQL query and execute it to seed your database with the data posted in this SQL Query: Follow this [link](https://github.com/NewForce-Cohort-8/tabloidmvc-thunder-strike/blob/main/SQL/02_TabloidMVC_Seed_Data.sql) .
5. Then, run the application in a browser window. You should see the 'Log in' page with a navigation bar at the top of the page. If not already logged out, log out (with the link in the navbar), and 'Log in' with the following credentials.  
email: admin@example.com.
6. Once you're logged in, click on "Posts" in the nav bar.
7. In order to protect our database while testing , please create a new post using the create button
    -  title the post "TEST ", has  content of "TEST CONTENT ", has current date selected , and other fields are optional 
    - next open a new query and  Run a select all to see if that created and refresh your page to make sure it is in the browser
    the select all query is : select * from post
    - move on after seeing the newly created post in query and browser .
 8. Inside the Post page, find your new post and click on the edit button on your new post.
7. This will redirect you to the Edit Post page where you can view the existing post info and Save/ Cancel buttons below.
8. Edit form fields, and REMEMBER to check the "Approved" checkbox  in the edit form in order to authorize the post in Post List.
9. Select Save button to finalize a post edit , and then you should be directed to Post List Page with your edited post. 
10. If you don't want to edit post, click on the Cancel button and you should be redirected back to the Post List to see all your posts. including your unedited post.

# Checklist:

- [x] I have opened ja-editPost-ticket8 in my local repository and made sure I have the SQL database and seeded it.
- [x] I have ran my application in a browser window to see a 'Log in' page
- [x] After logging in the appropriate credentials, selecting Posts in the navbar, directs me to a "Post LIST" page.
- [x] Selecting EDIT icon directs me to the Edit Post page where I can see my post to be edited.
- [x] Selecting Save Button leads me back to Post List page.

### CODE REVIEW

**Comment by sarahebrooks12** [comment]
- We want to protect our data in our DB so please include a SQL query and give instructions for example: (These are my rushing sorry)
1. Run a select all query `select * from post` and see what that brings back 
2. Create a new post that is titled "SWIFTY 4 LYFE", has a description of "GO TAYLOR'S BOYFRIEND"...
3. Run a select all to see if that created and refresh your page to make sure it is in the browser
4. Edit that post to say "SWIFTIE 4 LYFE" 
5.  Run a select all to see if that edited and refresh your page to make sure it is in the browser

**Review by CalBoyt — COMMENTED** [review]
Unfortunately, I was not able to get an edited post to save

**Review by andyhanks — APPROVED** [review]
This feature works as indicated.

**Review by sarahebrooks12 — APPROVED** [review]
Better - don't forget to add a select all statement at the end to make sure that your data in your DB is being changed

**Review by CalBoyt — APPROVED** [review]
Edit post works as described!

**Pull request merged**
